### ISSUE TITLE
CMakeLists.txt miss dependency to ${catkin_EXPORTED_TARGETS}

### ISSUE THREAD

**Issue by daenny** [CNURobotics/flexible_navigation#1]
I just tried to install the flexible navigation from an empty workspace. 
It fails to compile, since the messages/actions are not build before the rest.
You just need a dependency to in your CMakeLists.txt:
```
add_dependencies(your_program ${catkin_EXPORTED_TARGETS})
```
(see http://docs.ros.org/kinetic/api/catkin/html/howto/format2/building_msgs.html)

**Comment by dcconner** [comment]
fixed f103bd21945a860f0d0e7154fd95f6060689ba52 
Thanks.
