### ISSUE TITLE
How can i use the .cpp files instead of .py state in FlexBE_app?

### ISSUE THREAD

**Issue by luoyuzju** [CNURobotics/flexible_navigation#3]
How can i use the .cpp files instead of .py state in FlexBE_app?

**Comment by dcconner** [comment]
By "the .cpp" files do you mean the planner and controller code?

Those are computationally intensive, so they are not part of the FlexBE state machine.  Each state should be quick to calculate, so we use the action interface to the planner/controllers running as a separate node to do calculations asynchronously.  That allows other operations to run concurrently in the state machine if needed.

If you want a cpp calculation, just wrap it in Python node that calls the cpp function.  This is doable with standard python, but do beware of wrapping computationally expensive items in a FlexBE state implementation.

**Comment by luoyuzju** [comment]
Thank you ! I have run it successfully!
